#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         0
#bspc config window_gap           40
#bspc config split_ratio          0.5
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config top_padding          15
bspc config border_width         2
bspc config window_gap          0
bspc config presel_feedback_color "#ebdbb2"
bspc config normal_border_color "#000000"
bspc config active_border_color
bspc config focused_border_color "#EBDBB2"
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura state=tiled
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Pictures/Wallpapers/pixelcity.jpg &
xrandr --output DP-4 --mode 1920x1080 --rate 164.97 &
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true &
dunst &
numlockx &
setxkbmap -option grp:alt_caps_toggle -layout us,ir &
# ~/.config/polybar/launch.sh &
alacritty &
sleep 5; xmodmap ~/.Xmodmap

