#! /bin/sh
killall sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0
wmname LG3D
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#padding 
setxkbmap -option grp:alt_caps_toggle -layout us,ir
bspc config top_padding 15
bspc config left_padding 15
bspc config right_padding 15
bspc config bottom_padding 15
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Pictures/Wallpaper.jpg &
xrandr --output DP-4 --mode 1920x1080 --rate 164.97 &
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true &
# picom --experimental-backends &
/home/ethereal/.config/polybar/launch.sh --hack
dunst &
